baseURL = "https://sanbabyfrancis.github.io/"
languageCode = "en-us"
title = "sanbabyfrancis"
theme="archie"
copyright = "© sanbabyfrancis"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "⭐ [through the looking glass](https://en.wikipedia.org/wiki/Through_the_Looking-Glass) I see a world both familiar and different."
# Social Tags

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/sanbabyfrancis"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sanbabyfrancis"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/sanbabyfrancis"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:san.baby.francis123@gmail.com"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3          # Initially, 4
